/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tech.romashov;

import com.codeborne.selenide.Selenide;
import org.testng.annotations.Test;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    @Test
    public void itWorks() throws Exception {
        Selenide.open("http://localhost:8080/input");
    }
}
