/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tech.romashov;

import org.testng.annotations.Test;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.not;
import static org.hamcrest.Matchers.nullValue;

class AppTest {
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertThat("app should have a greeting", classUnderTest.getGreeting(), not(nullValue()));
    }
}
