---
name: CI/CD
'on':
  pull_request:
  push:

jobs:
  build:
    name: Run all tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3

      - name: Setup docker compose
        run: "docker compose version"

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto' # See 'Supported distributions' for available options
          java-version: '11'

      - uses: gradle/gradle-build-action@v2
        name: Setup Gradle
        with:
          gradle-version: 7.6.1

      - name: Run application
        run: "make run-application"

      - name: Run tests
        run: "make run-tests"

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: Devowelizer Test Tool # Name of the check run which will be created
          path: app/build/test-results/runTests/TEST-*.xml    # Path to test results
          reporter: java-junit        # Format of test results
